from __future__ import annotations

from io import BytesIO
from pathlib import Path

from fastapi.testclient import TestClient

from app.core.context import APIContext
from app.services.media import MediaService


# -----------------------------
# Unit tests for MediaService._invert_cuts
# These exercise the pure deadspace-inversion logic without touching ffmpeg.
# -----------------------------


def test_invert_cuts_single_middle_cut() -> None:
    keep = MediaService._invert_cuts([(2.0, 4.0)], total_duration_sec=10.0)
    assert keep == [(0.0, 2.0), (4.0, 10.0)]


def test_invert_cuts_leading_cut() -> None:
    keep = MediaService._invert_cuts([(0.0, 3.0)], total_duration_sec=10.0)
    assert keep == [(3.0, 10.0)]


def test_invert_cuts_trailing_cut() -> None:
    keep = MediaService._invert_cuts([(7.5, 10.0)], total_duration_sec=10.0)
    assert keep == [(0.0, 7.5)]


def test_invert_cuts_merges_overlaps() -> None:
    keep = MediaService._invert_cuts(
        [(1.0, 3.0), (2.5, 5.0)], total_duration_sec=10.0
    )
    assert keep == [(0.0, 1.0), (5.0, 10.0)]


def test_invert_cuts_drops_ranges_under_hundred_ms() -> None:
    # A 90ms cut is below the 100ms threshold and should be dropped.
    keep = MediaService._invert_cuts([(1.0, 1.09)], total_duration_sec=5.0)
    assert keep == [(0.0, 5.0)]


def test_invert_cuts_keeps_exact_hundred_ms_range() -> None:
    keep = MediaService._invert_cuts([(1.0, 1.1)], total_duration_sec=5.0)
    assert keep == [(0.0, 1.0), (1.1, 5.0)]


def test_invert_cuts_clamps_out_of_bounds() -> None:
    # Negative start and past-end ranges should be clamped in-bounds.
    keep = MediaService._invert_cuts(
        [(-5.0, 2.0), (8.0, 99.0)], total_duration_sec=10.0
    )
    assert keep == [(2.0, 8.0)]


def test_invert_cuts_full_clip_removed() -> None:
    # A cut covering the full clip should produce no keep ranges.
    keep = MediaService._invert_cuts([(0.0, 10.0)], total_duration_sec=10.0)
    assert keep == []


def test_invert_cuts_rejects_zero_duration() -> None:
    keep = MediaService._invert_cuts([(0.0, 1.0)], total_duration_sec=0.0)
    assert keep == []


def test_invert_cuts_sorts_unordered_input() -> None:
    keep = MediaService._invert_cuts(
        [(6.0, 7.0), (1.0, 2.0)], total_duration_sec=10.0
    )
    assert keep == [(0.0, 1.0), (2.0, 6.0), (7.0, 10.0)]


# -----------------------------
# API-level tests for the trim endpoint
# These use the StubMediaService from conftest so ffmpeg never runs.
# -----------------------------


def _upload_and_analyze(client: TestClient) -> str:
    upload = client.post(
        "/api/upload",
        files={"file": ("clip.mp4", BytesIO(b"fake-mp4"), "video/mp4")},
    ).json()
    analysis = client.post(
        "/api/analyze", json={"uploadId": upload["uploadId"]}
    ).json()
    # The immediate job service runs synchronously, so the record should be completed.
    loaded = client.get(f"/api/analysis/{analysis['analysisId']}").json()
    assert loaded["status"] == "completed"
    return analysis["analysisId"]


def test_trim_rejects_unknown_analysis(client: TestClient) -> None:
    response = client.post(
        "/api/analysis/deadbeefdeadbeefdeadbeefdeadbeef/trim",
        json={},
    )
    assert response.status_code == 404


def test_trim_rejects_non_hex_analysis_id(client: TestClient) -> None:
    # Non-hex ids should be treated as unknown analyses (path-traversal-safe).
    response = client.post(
        "/api/analysis/not-a-real-id-with-dashes/trim",
        json={},
    )
    assert response.status_code == 404


def test_storage_rejects_path_traversal_ids(test_context: APIContext) -> None:
    # Direct unit check: the validator must reject anything non-hex.
    import pytest

    storage = test_context.storage
    for bad_id in ("..", "../etc/passwd", "abc/../def", "hello!", ""):
        with pytest.raises(FileNotFoundError):
            storage.analysis_paths(bad_id)


def test_trim_applies_all_cuts_by_default(
    client: TestClient, test_context: APIContext
) -> None:
    analysis_id = _upload_and_analyze(client)
    payload = test_context.storage.read_analysis_payload(analysis_id)
    default_cut_count = len([cut for cut in payload.cutPlan if cut.defaultSelected])
    if not default_cut_count:
        # The stubbed fixtures should produce at least one deadspace range.
        # If they don't, the test is not meaningful, so skip gracefully.
        import pytest

        pytest.skip("No default-selected cuts generated by the stub fixture.")

    response = client.post(f"/api/analysis/{analysis_id}/trim", json={})
    assert response.status_code == 200
    body = response.json()
    assert body["analysisId"] == analysis_id
    assert body["trimmedVideoUrl"].startswith("/storage/")
    assert body["originalDurationSec"] == payload.video.durationSec
    assert body["removedSeconds"] >= 0
    assert body["trimmedDurationSec"] <= body["originalDurationSec"]
    assert len(body["appliedCuts"]) == default_cut_count

    # Subsequent fetches should surface the trimmed URL in artifacts.
    refreshed = client.get(f"/api/analysis/{analysis_id}").json()
    assert refreshed["payload"]["artifacts"]["trimmedVideoUrl"] == body["trimmedVideoUrl"]
    assert refreshed["payload"]["diagnostics"]["trimmedDurationSec"] == body["trimmedDurationSec"]
    assert refreshed["payload"]["exports"]


def test_trim_rejects_out_of_range_index(
    client: TestClient, test_context: APIContext
) -> None:
    analysis_id = _upload_and_analyze(client)
    payload = test_context.storage.read_analysis_payload(analysis_id)
    if not payload.deadspaceCuts:
        import pytest

        pytest.skip("No deadspace cuts generated by the stub fixture.")

    response = client.post(
        f"/api/analysis/{analysis_id}/trim",
        json={"cutIndices": [9999]},
    )
    assert response.status_code == 400


def test_trim_rejects_negative_index(
    client: TestClient, test_context: APIContext
) -> None:
    analysis_id = _upload_and_analyze(client)
    payload = test_context.storage.read_analysis_payload(analysis_id)
    if not payload.deadspaceCuts:
        import pytest

        pytest.skip("No deadspace cuts generated by the stub fixture.")

    response = client.post(
        f"/api/analysis/{analysis_id}/trim",
        json={"cutIndices": [-1]},
    )
    assert response.status_code == 400


def test_trim_rejects_empty_cut_indices_list(
    client: TestClient, test_context: APIContext
) -> None:
    analysis_id = _upload_and_analyze(client)
    payload = test_context.storage.read_analysis_payload(analysis_id)
    if not payload.deadspaceCuts:
        import pytest

        pytest.skip("No deadspace cuts generated by the stub fixture.")

    response = client.post(
        f"/api/analysis/{analysis_id}/trim",
        json={"cutIndices": []},
    )
    assert response.status_code == 400


def test_trim_deduplicates_repeated_indices(
    client: TestClient, test_context: APIContext
) -> None:
    analysis_id = _upload_and_analyze(client)
    payload = test_context.storage.read_analysis_payload(analysis_id)
    if not payload.deadspaceCuts:
        import pytest

        pytest.skip("No deadspace cuts generated by the stub fixture.")

    response = client.post(
        f"/api/analysis/{analysis_id}/trim",
        json={"cutIndices": [0, 0, 0]},
    )
    assert response.status_code == 200
    assert len(response.json()["appliedCuts"]) == 1


def test_trim_accepts_cut_ids_and_persists_export_metadata(
    client: TestClient, test_context: APIContext
) -> None:
    analysis_id = _upload_and_analyze(client)
    payload = test_context.storage.read_analysis_payload(analysis_id)
    if not payload.cutPlan:
        import pytest

        pytest.skip("No cut plan generated by the stub fixture.")

    selected = payload.cutPlan[:2]
    response = client.post(
        f"/api/analysis/{analysis_id}/trim",
        json={"cutIds": [cut.id for cut in selected]},
    )
    assert response.status_code == 200
    body = response.json()
    assert [cut["id"] for cut in body["appliedCuts"]] == [cut.id for cut in selected]

    refreshed = test_context.storage.read_analysis_payload(analysis_id)
    assert refreshed.exports
    assert refreshed.exports[-1].selectedCutIds == [cut.id for cut in selected]
